### ISSUE TITLE
TypeError: string indices must be integers, not 'str'` when creating a new Commit Project

### ISSUE THREAD

**Issue by destinedcodes** [The-Commit-Company/commit#62]
**Description:**

I encountered a `TypeError` while trying to create a new Commit Project in the Commit Frappe app. The error occurs during the insertion process of the document. This might be due to a missing or incorrect type handling in the code, but it could also be a lack of clear documentation on how to properly set up and use the app.

**Steps to Reproduce:**

1. Create a new Frappe bench.
2. Install the Commit app.
3. Create a new site with the Commit app installed.
4. Create an organization.
5. Attempt to create a new Commit Project.

**Traceback:**

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_method("before_insert")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/commit/commit/commit/doctype/commit_project/commit_project.py", line 14, in before_insert
    self.app_name = get_name_of_app(self.org, self.repo_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/commit/commit/api/code_analysis.py", line 16, in get_name_of_app
    if file["name"] == "pyproject.toml":
       ~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

- It seems that the error is related to how the `file` variable is being handled in the `get_name_of_app` function. It might be treated as a string rather than an iterable dictionary or list.
- This could be due to incorrect data handling or a missing type check in the code.
- If there is a specific setup or step I missed, please provide guidance on the correct procedure.
- I am willing to contribute to the documentation after understanding and resolving this issue.

Thank you!

**Comment by sumitjain236** [comment]
Thank you @destinedcodes for reporting issue, will look into this.

**Comment by destinedcodes** [comment]
I am willing to write a fix for this. Can the issue be assigned to me?

**Comment by sumitjain236** [comment]
Yes you can contribute and create a PR, I will review and merge if solution is good
